//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HieuVeBan.Data.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptToMigration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptToMigration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HieuVeBan.Data.Scripts.ScriptToMigration", typeof(ScriptToMigration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO administrative_regions(id,name,name_en,code_name,code_name_en) VALUES(1,N&apos;Đông Bắc Bộ&apos;,N&apos;Northeast&apos;,N&apos;dong_bac_bo&apos;,N&apos;northest&apos;);
        ///INSERT INTO administrative_regions(id,name,name_en,code_name,code_name_en) VALUES(2,N&apos;Tây Bắc Bộ&apos;,N&apos;Northwest&apos;,N&apos;tay_bac_bo&apos;,N&apos;northwest&apos;);
        ///INSERT INTO administrative_regions(id,name,name_en,code_name,code_name_en) VALUES(3,N&apos;Đồng bằng sông Hồng&apos;,N&apos;Red River Delta&apos;,N&apos;dong_bang_song_hong&apos;,N&apos;red_river_delta&apos;);
        ///INSERT INTO administrative_regions(id,name,name_en,code_na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedDataAdministrativeRegion {
            get {
                return ResourceManager.GetString("SeedDataAdministrativeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO administrative_units(id,full_name,full_name_en,short_name,short_name_en,code_name,code_name_en) VALUES(1,N&apos;Thành phố trực thuộc trung ương&apos;,N&apos;Municipality&apos;,N&apos;Thành phố&apos;,N&apos;City&apos;,N&apos;thanh_pho_truc_thuoc_trung_uong&apos;,N&apos;municipality&apos;);
        ///INSERT INTO administrative_units(id,full_name,full_name_en,short_name,short_name_en,code_name,code_name_en) VALUES(2,N&apos;Tỉnh&apos;,N&apos;Province&apos;,N&apos;Tỉnh&apos;,N&apos;Province&apos;,N&apos;tinh&apos;,N&apos;province&apos;);
        ///INSERT INTO administrative_units(id,full_name,full_name_en,short_name,short_name_en,code_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedDataAdministrativeUnit {
            get {
                return ResourceManager.GetString("SeedDataAdministrativeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO provinces(id,code,name,name_en,full_name,full_name_en,code_name,administrative_unit_id,administrative_region_id) VALUES
        ///(1,&apos;01&apos;,N&apos;Hà Nội&apos;,N&apos;Ha Noi&apos;,N&apos;Thành phố Hà Nội&apos;,N&apos;Ha Noi City&apos;,&apos;ha_noi&apos;,1,3),
        ///(2,&apos;02&apos;,N&apos;Hà Giang&apos;,N&apos;Ha Giang&apos;,N&apos;Tỉnh Hà Giang&apos;,N&apos;Ha Giang Province&apos;,&apos;ha_giang&apos;,2,1),
        ///(3,&apos;04&apos;,N&apos;Cao Bằng&apos;,N&apos;Cao Bang&apos;,N&apos;Tỉnh Cao Bằng&apos;,N&apos;Cao Bang Province&apos;,&apos;cao_bang&apos;,2,1),
        ///(4,&apos;06&apos;,N&apos;Bắc Kạn&apos;,N&apos;Bac Kan&apos;,N&apos;Tỉnh Bắc Kạn&apos;,N&apos;Bac Kan Province&apos;,&apos;bac_kan&apos;,2,1),
        ///(5,&apos;08&apos;,N&apos;Tuyên Quang&apos;,N&apos;Tuyen Quang&apos;,N&apos;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedDataProvince {
            get {
                return ResourceManager.GetString("SeedDataProvince", resourceCulture);
            }
        }
    }
}
